namespace web.Components.Shared;

public record ApiErrorResponse(string Message);

public record SearchReplacementRequest(string Reason, string Notes, string? IssueType = null);
public record LibraryRemediationOperatorReviewRequest(string Outcome);

public record LibraryRemediationIntentDto(
    string IssueType,
    string RequestedAction,
    string ReasonCategory,
    string Confidence,
    bool ShouldSearchNow,
    bool ShouldBlacklistCurrentRelease,
    bool NeedsManualReview,
    bool NotesRecordedOnly,
    string PolicySummary,
    string NotesHandling,
    string ProfileDecision,
    string ProfileSummary,
    string PolicyState,
    string NextActionSummary);

public record LibraryItemRemediationResponse(
    long LibraryItemId,
    bool Success,
    string ServiceKey,
    string ServiceDisplayName,
    string CommandName,
    int? ExternalItemId,
    bool LookedUpRemotely,
    string Reason,
    string Notes,
    string Message,
    LibraryRemediationIntentDto? Intent = null,
    string SearchStatusHint = "");

public record LibraryRemediationJobDto(
    long Id,
    long LibraryItemId,
    long? LibraryIssueId,
    string ServiceKey,
    string ServiceDisplayName,
    long? IntegrationId,
    string RequestedAction,
    string CommandName,
    int? ExternalItemId,
    string IssueType,
    string Reason,
    string Notes,
    string ReasonCategory,
    string Confidence,
    bool ShouldSearchNow,
    bool ShouldBlacklistCurrentRelease,
    bool NeedsManualReview,
    bool NotesRecordedOnly,
    bool LookedUpRemotely,
    string PolicySummary,
    string NotesHandling,
    string ProfileDecision,
    string ProfileSummary,
    string Status,
    string SearchStatus,
    string BlacklistStatus,
    string OutcomeSummary,
    string ResultMessage,
    int? ProviderCommandId,
    string ProviderCommandStatus,
    string ProviderCommandSummary,
    DateTimeOffset? ProviderCommandCheckedAtUtc,
    string VerificationStatus,
    string VerificationSummary,
    string VerificationDetailsJson,
    DateTimeOffset? VerificationCheckedAtUtc,
    string LoopbackStatus,
    string LoopbackSummary,
    string ReleaseSummary,
    string OperatorReviewStatus,
    string OperatorReviewSummary,
    string OperatorReviewedBy,
    DateTimeOffset? OperatorReviewedAtUtc,
    string RequestedBy,
    DateTimeOffset RequestedAtUtc,
    DateTimeOffset? FinishedAtUtc,
    DateTimeOffset? LastCheckedAtUtc,
    DateTimeOffset UpdatedAtUtc);
