namespace web.Components.Shared;

public record MediaItemDetailDto(
    long Id,
    string CanonicalKey,
    string MediaType,
    string DisplayTitle,
    string Title,
    string SortTitle,
    int? Year,
    int? TmdbId,
    int? TvdbId,
    string ImdbId,
    string PlexRatingKey,
    string Description,
    string DescriptionSourceService,
    double? RuntimeMinutes,
    double? ActualRuntimeMinutes,
    IReadOnlyList<string> AudioLanguages,
    IReadOnlyList<string> SubtitleLanguages,
    string PlayabilityScore,
    int PlayabilityNumericScore,
    string PlayabilitySummary,
    DateTimeOffset? PlayabilityCheckedAtUtc,
    IReadOnlyList<string> PlayabilityReasons,
    string PlayabilityVideoCodec,
    IReadOnlyList<string> PlayabilityAudioCodecs,
    IReadOnlyList<string> PlayabilitySubtitleCodecs,
    bool IsAvailable,
    string QualityProfile,
    DateTimeOffset? SourceUpdatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    string PrimaryFilePath,
    bool LocalFileExists,
    IReadOnlyList<string> SourceServices,
    string ContentRating);

public record LibraryItemSourceLinkDto(
    long Id,
    long LibraryItemId,
    long IntegrationId,
    string ServiceKey,
    string InstanceName,
    string SourceTitle,
    string SourceSortTitle,
    string ExternalId,
    string ExternalType,
    DateTimeOffset? ExternalUpdatedAtUtc,
    DateTimeOffset LastSeenAtUtc,
    bool IsDeletedAtSource);


public record BazarrSubtitleStatusDto(
    long LibraryItemId,
    bool Configured,
    bool HasMatch,
    string ServiceDisplayName,
    string InstanceName,
    string TargetKind,
    int? ExternalId,
    bool Monitored,
    IReadOnlyList<string> AvailableSubtitles,
    IReadOnlyList<string> MissingSubtitles,
    int MissingEpisodeCount,
    int EpisodeFileCount,
    string Status,
    string Summary,
    DateTimeOffset CheckedAtUtc);
